[tool.ruff]
line-length = 120
target-version = "py311"
exclude = [".venv"]

[tool.ruff.lint]
select = ["E", "F", "B", "I"]

[tool.ruff.format]
preview = true

[tool.ruff.lint.isort]
lines-between-types = 1